// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWpxDqGEtOL2emC-ptGmMvYAQX7_OiJSc',
    appId: '1:584729223143:web:0772419b20928ea4cfa742',
    messagingSenderId: '584729223143',
    projectId: 'istegram-8ff6e',
    authDomain: 'istegram-8ff6e.firebaseapp.com',
    storageBucket: 'istegram-8ff6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SWYWazjmeXSDu1K2g_zDM5ARa6JLMlM',
    appId: '1:584729223143:android:71cde2d6be3f3ef8cfa742',
    messagingSenderId: '584729223143',
    projectId: 'istegram-8ff6e',
    storageBucket: 'istegram-8ff6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkErn0SGuBH70fN2FZ-StBV_p23ZbmXNI',
    appId: '1:584729223143:ios:a06d38c22f9b5722cfa742',
    messagingSenderId: '584729223143',
    projectId: 'istegram-8ff6e',
    storageBucket: 'istegram-8ff6e.appspot.com',
    iosBundleId: 'com.example.istegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkErn0SGuBH70fN2FZ-StBV_p23ZbmXNI',
    appId: '1:584729223143:ios:a06d38c22f9b5722cfa742',
    messagingSenderId: '584729223143',
    projectId: 'istegram-8ff6e',
    storageBucket: 'istegram-8ff6e.appspot.com',
    iosBundleId: 'com.example.istegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWpxDqGEtOL2emC-ptGmMvYAQX7_OiJSc',
    appId: '1:584729223143:web:d9cd24ca9b1557b2cfa742',
    messagingSenderId: '584729223143',
    projectId: 'istegram-8ff6e',
    authDomain: 'istegram-8ff6e.firebaseapp.com',
    storageBucket: 'istegram-8ff6e.appspot.com',
  );
}
